# Generated by Django 4.1.7 on 2023-05-23 22:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.IntegerField(choices=[(0, 'bueno'), (1, 'regular'), (2, 'malo')], default=0)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tiquet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assunto', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DNI', models.CharField(max_length=100)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.IntegerField(choices=[(0, 'pendiente'), (1, 'validada'), (2, 'pagada'), (3, 'cancelada')], default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicEngineApp.material')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicEngineApp.sala')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicEngineApp.tecnico')),
            ],
        ),
        migrations.CreateModel(
            name='LineaFactura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicEngineApp.factura')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicEngineApp.tecnico')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='lineas',
            field=models.ManyToManyField(related_name='lineas', to='MusicEngineApp.lineafactura'),
        ),
        migrations.AddField(
            model_name='factura',
            name='reserva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MusicEngineApp.reserva'),
        ),
        migrations.CreateModel(
            name='ConversacionTiquet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('tiquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicEngineApp.tiquet')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
