# Generated by Django 4.1.7 on 2023-04-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicEngineApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='estado',
            field=models.IntegerField(choices=[(0, 'bueno'), (1, 'regular'), (2, 'malo')], default=0),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
