# Generated by Django 4.1.7 on 2023-05-23 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MusicEngineApp', '0002_tiquet_conversacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiquet',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
