# Generated by Django 4.1.7 on 2023-05-23 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicEngineApp', '0003_alter_tiquet_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiquet',
            name='conversacion',
        ),
    ]
