# Generated by Django 4.1.7 on 2023-04-27 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MusicEngineApp', '0003_factura_lineafactura_factura_lineas_factura_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='DNI',
            field=models.CharField(default='11111111D', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='nombre_cliente',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='reserva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MusicEngineApp.reserva'),
        ),
    ]
