# Generated by Django 4.1.7 on 2023-04-27 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicEngineApp', '0004_factura_dni_factura_nombre_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='DNI',
            new_name='dni',
        ),
    ]
