# Generated by Django 4.1.7 on 2023-05-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicEngineApp', '0005_rename_dni_factura_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.IntegerField(choices=[(0, 'pendiente'), (1, 'validada'), (2, 'pagada')], default=0),
        ),
    ]
