# Generated by Django 4.1.7 on 2023-05-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicEngineApp', '0006_reserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.IntegerField(choices=[(0, 'pendiente'), (1, 'validada'), (2, 'pagada'), (3, 'cancelada')], default=0),
        ),
    ]
