# Generated by Django 4.1.7 on 2023-05-23 19:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MusicEngineApp', '0007_alter_reserva_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiquet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assunto', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ConversacionTiquet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('tiquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicEngineApp.tiquet')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
